# Generated by Django 6.1 on 2026-08-28 01:46

import django.db.models.deletion
import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("vinta_django_questionnaires", "0009_integration_scope"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettingsLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text='How this level is referred to, such as "organization" or "team".',
                        max_length=100,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="name"
                    ),
                ),
                (
                    "parent_lookup",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='The ORM path from this level\'s model to the parent level\'s instance, such as "organization" or "team__organization". Every hop has to be a foreign key or a one-to-one, because the resolver follows it in SQL. Leave it empty when the parent is the global level.',
                        max_length=255,
                        verbose_name="parent lookup",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        help_text="The model this level attaches to. Leave it empty for the global level, which holds the values everything else falls back to.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cascading_settings_levels",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="The level this one inherits from.",
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="vinta_django_cascading_settings.settingslevel",
                        verbose_name="parent",
                    ),
                ),
            ],
            options={
                "verbose_name": "settings level",
                "verbose_name_plural": "settings levels",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SettingsSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text='How this set of settings is referred to, such as "billing".',
                        max_length=100,
                        unique=True,
                        verbose_name="key",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive schemas are ignored when a key is looked up without one.",
                        verbose_name="is active",
                    ),
                ),
                (
                    "levels",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The levels allowed to hold values for these settings. Leave it empty to allow every level.",
                        related_name="schemas",
                        to="vinta_django_cascading_settings.settingslevel",
                        verbose_name="levels",
                    ),
                ),
                (
                    "questionnaire",
                    models.OneToOneField(
                        help_text="The questionnaire whose questions are the settings.",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="settings_schema",
                        to="vinta_django_questionnaires.questionnaire",
                        verbose_name="questionnaire",
                    ),
                ),
            ],
            options={
                "verbose_name": "settings schema",
                "verbose_name_plural": "settings schemas",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="ScopedSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "object_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The holder's primary key as the database writes it. Empty when global.",
                        max_length=191,
                        verbose_name="object id",
                    ),
                ),
                (
                    "scope_key",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        default="",
                        help_text="The tenant these values belong to, copied from the response. Empty at the global level, whose values are the installation's.",
                        max_length=255,
                        verbose_name="scope key",
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
                (
                    "response",
                    models.OneToOneField(
                        help_text="The response whose answers are these values.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_settings",
                        to="vinta_django_questionnaires.questionnaireresponse",
                        verbose_name="response",
                    ),
                ),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scoped_settings",
                        to="vinta_django_cascading_settings.settingslevel",
                        verbose_name="level",
                    ),
                ),
                (
                    "schema",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoped_settings",
                        to="vinta_django_cascading_settings.settingsschema",
                        verbose_name="schema",
                    ),
                ),
            ],
            options={
                "verbose_name": "scoped settings",
                "verbose_name_plural": "scoped settings",
                "ordering": ["schema", "level", "object_id"],
            },
        ),
        migrations.CreateModel(
            name="SettingLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("key", models.SlugField(max_length=100, verbose_name="key")),
                (
                    "reason",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="reason"
                    ),
                ),
                (
                    "scoped_settings",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locks",
                        to="vinta_django_cascading_settings.scopedsettings",
                        verbose_name="scoped settings",
                    ),
                ),
            ],
            options={
                "verbose_name": "setting lock",
                "verbose_name_plural": "setting locks",
                "ordering": ["scoped_settings", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scoped_settings", "key"),
                        name="unique_setting_lock_per_key",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="settingslevel",
            constraint=models.UniqueConstraint(
                django.db.models.functions.comparison.Coalesce(
                    "content_type", models.Value(0), output_field=models.IntegerField()
                ),
                name="unique_settings_level_per_content_type",
            ),
        ),
        migrations.AddIndex(
            model_name="scopedsettings",
            index=models.Index(
                fields=["content_type", "object_id"], name="cascading_settings_holder"
            ),
        ),
        migrations.AddConstraint(
            model_name="scopedsettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_type__isnull", False)),
                fields=("schema", "content_type", "object_id"),
                name="unique_scoped_settings_per_object_and_schema",
            ),
        ),
        migrations.AddConstraint(
            model_name="scopedsettings",
            constraint=models.UniqueConstraint(
                condition=models.Q(("content_type__isnull", True)),
                fields=("schema",),
                name="unique_global_settings_per_schema",
            ),
        ),
    ]
